# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  tbnews-csharp:
    image: tabnews-dotnet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:      
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Production